extends Node2D

var dialogue_1 = [
	{
		"Name": "",
		"Expression": "",
		"Position": "",
		"Choices": "",
		"Text": "O Ano é 2104. ",
		"Music": "",
		"SFX": "",
	},
	{
		"Name": "Radialista",
		"Expression": "",
		"Position": "",
		"Choices": "",
		"Text": "“A democracia ruiu, e o mundo abraçou o totalitarismo.” ",
		"Music": "",
		"SFX": "",
	},
	{
		"Name": "Radialista",
		"Expression": "",
		"Position": "",
		"Choices": "",
		"Text": "A primeira vítima foi a liberdade, a segunda, a arte. ",
		"Music": "",
		"SFX": "",
	},
	{
		"Name": "",
		"Expression": "",
		"Position": "",
		"Choices": "",
		"Text": "“ A homogenização é sem igual. ” ",
		"Music": "",
		"SFX": "botao",
	},
	{
		"Name": "",
		"Expression": "",
		"Position": "",
		"Choices": "",
		"Text": "“ Não há beleza ou criatividade. ” ",
		"Music": "",
		"SFX": "botao",
	},
	{
		"Name": "",
		"Expression": "",
		"Position": "",
		"Choices": "",
		"Text": "“ Mas em algum lugar, ainda existe esperança... ” ",
		"Music": "",
		"SFX": "botao",
	},
	{
		"Name": "",
		"Expression": "",
		"Position": "",
		"Choices": "",
		"Text": "“ A última estação. ” ",
		"Music": "",
		"SFX": "botao",
	},
	{
		"Name": "",
		"Expression": "",
		"Position": "",
		"Choices": "",
		"Text": "Um homem, numa sala operacional de uma estação de rádio, mexe nos computadores. ",
		"Music": "",
		"SFX": "botao",
	},
	{
		"Name": "",
		"Expression": "",
		"Position": "",
		"Choices": "",
		"Text": "“ 'Não temos muito tempo.' ” ",
		"Music": "",
		"SFX": "botao",
	},
	{
		"Name": "",
		"Expression": "",
		"Position": "",
		"Choices": "",
		"Text": "'Essa pode ser a nossa última esperança… ' ",
		"Music": "",
		"SFX": "botao",
	},
	{
		"Name": "",
		"Expression": "",
		"Position": "",
		"Choices": "",
		"Text": "O radialista pressiona um botão. ",
		"Music": "",
		"SFX": "botao",
	},
	{
		"Name": "",
		"Expression": "",
		"Position": "",
		"Choices": "",
		"Text": "'E… enviado.' ",
		"Music": "",
		"SFX": "botao",
	}
] 

